### ISSUE TITLE
Linux::Systemd::Journal::Read seek_tail failure

### ISSUE THREAD

**Issue by anaselli** [ioanrogers/Linux-Systemd-Journal#1]
Can't locate object method "_j" via package "Linux::Systemd::Journal::Read" at /home/anaselli/perl5/lib/perl5/x86_64-linux-thread-multi/Linux/Systemd/Journal/Read.pm line 31

**Comment by anaselli** [comment]
Possible patch here
https://gist.github.com/anaselli/308c56f64acaa1a15280

**Comment by ioanrogers** [comment]
Hi @anaselli , sorry I took so long to get to this. I've just released 0.003 which fixes this.

Thanks!
